import { DisasterEvent } from '../src/types.js';

export const fallbackDisasterEvents: DisasterEvent[] = [
  {
    id: 'usgs-nc75148921',
    title: 'M 5.8 - 42 km ESE of Kokopo, Papua New Guinea',
    category: 'Earthquakes',
    lat: -4.48,
    lon: 152.63,
    date: new Date(Date.now() - 18 * 60000).toISOString(),
    link: 'https://earthquake.usgs.gov/earthquakes/eventpage/nc75148921',
    detail: 'M 5.8',
    source: 'USGS Earthquakes',
    magnitude: 5.8,
    severityLevel: 'critical',
  },
  {
    id: 'usgs-in20241002',
    title: 'M 4.7 - 78 km NNE of Champhai, Mizoram, India',
    category: 'Earthquakes',
    lat: 23.98,
    lon: 93.52,
    date: new Date(Date.now() - 65 * 60000).toISOString(),
    link: 'https://earthquake.usgs.gov/earthquakes',
    detail: 'M 4.7',
    source: 'USGS Earthquakes',
    magnitude: 4.7,
    severityLevel: 'high',
  },
  {
    id: 'eonet-EONET_6412',
    title: 'Tropical Cyclone Kenneth',
    category: 'Severe Storms',
    lat: 16.2,
    lon: 82.5,
    date: new Date(Date.now() - 110 * 60000).toISOString(),
    link: 'https://eonet.gsfc.nasa.gov/api/v3/events/EONET_6412',
    detail: 'Category 3 Storm',
    source: 'NASA EONET',
    severityLevel: 'critical',
  },
  {
    id: 'eonet-EONET_6399',
    title: 'Monsoon Flood Wave in Brahmaputra Basin, Assam',
    category: 'Floods',
    lat: 26.2,
    lon: 91.75,
    date: new Date(Date.now() - 145 * 60000).toISOString(),
    link: 'https://eonet.gsfc.nasa.gov/api/v3/events',
    detail: 'Water level > 10.4m',
    source: 'NASA EONET',
    severityLevel: 'high',
  },
  {
    id: 'eonet-EONET_6382',
    title: 'Bushfire Complex - East Coast New South Wales',
    category: 'Wildfires',
    lat: -33.86,
    lon: 150.8,
    date: new Date(Date.now() - 210 * 60000).toISOString(),
    link: 'https://eonet.gsfc.nasa.gov/api/v3/events',
    detail: 'Active containment: 35%',
    source: 'NASA EONET',
    severityLevel: 'high',
  },
  {
    id: 'eonet-EONET_6350',
    title: 'Mount Semeru Pyroclastic Activity, East Java',
    category: 'Volcanoes',
    lat: -8.108,
    lon: 112.92,
    date: new Date(Date.now() - 320 * 60000).toISOString(),
    link: 'https://eonet.gsfc.nasa.gov/api/v3/events',
    detail: 'Ash plume 4.5km altitude',
    source: 'NASA EONET',
    severityLevel: 'critical',
  },
  {
    id: 'usgs-us7000nvl4',
    title: 'M 5.1 - 12 km SSW of Hualien City, Taiwan',
    category: 'Earthquakes',
    lat: 23.89,
    lon: 121.57,
    date: new Date(Date.now() - 410 * 60000).toISOString(),
    link: 'https://earthquake.usgs.gov/earthquakes',
    detail: 'M 5.1',
    source: 'USGS Earthquakes',
    magnitude: 5.1,
    severityLevel: 'high',
  },
  {
    id: 'eonet-EONET_6291',
    title: 'Wildfire - Sierra National Forest, California',
    category: 'Wildfires',
    lat: 37.25,
    lon: -119.31,
    date: new Date(Date.now() - 500 * 60000).toISOString(),
    link: 'https://eonet.gsfc.nasa.gov/api/v3/events',
    detail: '4,200 acres burned',
    source: 'NASA EONET',
    severityLevel: 'high',
  },
  {
    id: 'eonet-EONET_6284',
    title: 'Flash Floods - Valencia Province, Spain',
    category: 'Floods',
    lat: 39.46,
    lon: -0.37,
    date: new Date(Date.now() - 650 * 60000).toISOString(),
    link: 'https://eonet.gsfc.nasa.gov/api/v3/events',
    detail: 'Severe river surge',
    source: 'NASA EONET',
    severityLevel: 'critical',
  },
  {
    id: 'usgs-us6000m8k9',
    title: 'M 4.9 - 110 km W of Kyaukpyu, Myanmar',
    category: 'Earthquakes',
    lat: 19.42,
    lon: 92.56,
    date: new Date(Date.now() - 720 * 60000).toISOString(),
    link: 'https://earthquake.usgs.gov/earthquakes',
    detail: 'M 4.9',
    source: 'USGS Earthquakes',
    magnitude: 4.9,
    severityLevel: 'moderate',
  }
];
