import { DisasterEvent } from '../types';
import { colorFor, getSeverityBadge } from '../utils/colors';
import { formatDateTime, timeAgo } from '../utils/time';
import { X, ExternalLink, MapPin, Calendar, Activity, ShieldCheck, Copy, Check } from 'lucide-react';
import { useState } from 'react';

interface EventDetailModalProps {
  event: DisasterEvent | null;
  onClose: () => void;
  onFlyTo: (event: DisasterEvent) => void;
}

export default function EventDetailModal({
  event,
  onClose,
  onFlyTo,
}: EventDetailModalProps) {
  const [copied, setCopied] = useState(false);
  if (!event) return null;

  const color = colorFor(event.category);
  const severity = getSeverityBadge(event.severityLevel);

  const getEmergencyActionList = (category: string) => {
    switch (category.toLowerCase()) {
      case 'earthquakes':
        return [
          'Drop, Cover, and Hold On beneath sturdy furniture or interior walls.',
          'Shut off gas lines and electrical mains if structural compromise is detected.',
          'Expect seismic aftershocks; avoid damaged buildings and unreinforced masonry.',
          'Activate local Aapda Mitra volunteers and check on senior citizens / vulnerable individuals.',
        ];
      case 'floods':
        return [
          'Move immediately to designated high ground or evacuation shelters.',
          'Never attempt to drive or walk through flood waters (Turn Around, Don\'t Drown).',
          'Disconnect electrical appliances to prevent short circuits and electrocution.',
          'Coordinate relief boats and water filtration kits with district administration.',
        ];
      case 'severe storms':
      case 'cyclones':
        return [
          'Secure loose roof sheets, solar panels, and external equipment.',
          'Prepare emergency GO-bag with torch, battery radio, water, and first aid.',
          'Stay indoors away from windows; keep satellite phones or ham radio ready.',
          'Monitor IMD / NDRF coastal radar bulletins every 3 hours.',
        ];
      case 'wildfires':
        return [
          'Evacuate immediately upon local authority broadcast; close all doors & vents.',
          'Wear N95 or P100 masks to filter dangerous particulate matter (PM2.5).',
          'Establish firebreaks and buffer zones around residential clusters.',
          'Keep livestock and pets in pre-cleared containment pastures.',
        ];
      default:
        return [
          'Maintain situational awareness through regional disaster management channels.',
          'Verify official bulletins before forwarding emergency advisories.',
          'Keep emergency communication devices fully charged.',
        ];
    }
  };

  const handleCopyTelemetry = () => {
    const text = `[RAKSHANET ALERT]
Incident: ${event.title}
Category: ${event.category}
Coordinates: ${event.lat}, ${event.lon}
Detail: ${event.detail || 'N/A'}
Date: ${event.date}
Source: ${event.source || 'NASA / USGS'}
Telemetry generated by RakshaNet (SIH-1687)`;
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-[600] flex items-center justify-center p-4 bg-black/70 backdrop-blur-sm animate-fadeIn">
      <div className="relative w-full max-w-lg bg-[#0F1B29] border border-[#22374A] rounded-xl shadow-2xl overflow-hidden flex flex-col max-h-[90vh]">
        {/* Header with category accent */}
        <div
          className="p-4 border-b border-[#22374A] flex items-start justify-between gap-3"
          style={{ borderTop: `4px solid ${color}` }}
        >
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span
                className="text-xs font-mono font-bold tracking-wider uppercase px-2 py-0.5 rounded"
                style={{ backgroundColor: `${color}20`, color: color }}
              >
                {event.category}
              </span>
              <span className={`text-[11px] font-mono font-bold px-2 py-0.5 rounded border ${severity.bg} ${severity.text}`}>
                {severity.label}
              </span>
              <span className="text-xs font-mono text-slate-400">
                {timeAgo(event.date)}
              </span>
            </div>
            <h2 className="text-base font-display font-bold text-white leading-snug">
              {event.title}
            </h2>
          </div>

          <button
            onClick={onClose}
            className="p-1 rounded-md text-slate-400 hover:text-white hover:bg-[#16283A] transition"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Modal Body */}
        <div className="p-4 overflow-y-auto space-y-4 font-mono text-xs">
          {/* Geolocation & Telemetry Grid */}
          <div className="grid grid-cols-2 gap-2.5 p-3 rounded-lg bg-[#16283A] border border-[#22374A]">
            <div className="flex items-center gap-2">
              <MapPin className="w-4 h-4 text-cyan-400 shrink-0" />
              <div>
                <span className="text-[10px] text-slate-400 block">COORDINATES</span>
                <span className="text-slate-200 font-bold">{event.lat.toFixed(4)}°, {event.lon.toFixed(4)}°</span>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <Activity className="w-4 h-4 text-amber-400 shrink-0" />
              <div>
                <span className="text-[10px] text-slate-400 block">MAGNITUDE / METRIC</span>
                <span className="text-slate-200 font-bold">{event.detail || 'Active Geo-event'}</span>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <Calendar className="w-4 h-4 text-emerald-400 shrink-0" />
              <div>
                <span className="text-[10px] text-slate-400 block">TIME (UTC / LOCAL)</span>
                <span className="text-slate-200 text-[11px]">{formatDateTime(event.date)}</span>
              </div>
            </div>

            <div className="flex items-center gap-2">
              <ShieldCheck className="w-4 h-4 text-indigo-400 shrink-0" />
              <div>
                <span className="text-[10px] text-slate-400 block">DATA PROVIDER</span>
                <span className="text-slate-200 font-semibold">{event.source || 'Aggregated Feed'}</span>
              </div>
            </div>
          </div>

          {/* Emergency Response & Evacuation Guidelines */}
          <div className="p-3.5 rounded-lg bg-[#122232] border border-cyan-900/40">
            <h3 className="font-display font-semibold text-cyan-300 text-xs tracking-wide uppercase mb-2 flex items-center gap-1.5">
              <ShieldCheck className="w-4 h-4 text-cyan-400" />
              <span>NDRF / Field Standard Operating Guidelines</span>
            </h3>
            <ul className="space-y-1.5 text-slate-300 text-[11px]">
              {getEmergencyActionList(event.category).map((tip, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-cyan-400 font-bold">&bull;</span>
                  <span>{tip}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Modal Footer Controls */}
        <div className="p-3 bg-[#0B1420] border-t border-[#22374A] flex items-center justify-between gap-2 font-mono text-xs">
          <button
            onClick={handleCopyTelemetry}
            className="flex items-center gap-1.5 px-3 py-1.5 rounded bg-[#16283A] hover:bg-[#22374A] text-slate-300 border border-[#22374A] transition"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied' : 'Copy Telemetry'}</span>
          </button>

          <div className="flex items-center gap-2">
            {event.link && (
              <a
                href={event.link}
                target="_blank"
                rel="noopener noreferrer"
                className="flex items-center gap-1 px-3 py-1.5 rounded bg-slate-800 hover:bg-slate-700 text-slate-300 transition"
              >
                <span>Upstream Source</span>
                <ExternalLink className="w-3 h-3" />
              </a>
            )}

            <button
              onClick={() => {
                onFlyTo(event);
                onClose();
              }}
              className="flex items-center gap-1.5 px-3.5 py-1.5 rounded bg-cyan-500 hover:bg-cyan-400 text-[#0B1420] font-bold transition cursor-pointer"
            >
              <MapPin className="w-3.5 h-3.5" />
              <span>Fly on Map</span>
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
